Glow-Carrots-App/glow-web

- pages/eat/index.js
Ran and tested route using localhost.
> GS-38: Add an eat page

- pages/sign-in/index.js
This closes https://spacem8s.atlassian.net/browse/GS-4
> GS-4: Add a signin page

- pages/settings/delete-account/index.js
This closes out https://spacem8s.atlassian.net/browse/GS-71
> GS-71: Create delete account subpage of settings page

- pages/settings/logout/index.js
This closes https://spacem8s.atlassian.net/browse/GS-69
> GS-69: Create a logout subpage of Settings

- pages/settings/feedback/index.js
> GS-65: Add feedback subpage to settings

- pages/settings/change-goal/index.js
> GS-62: Add change goal subpage to settings

- components/CreateAccountForm/index.js
- components/CreateAccountForm/styles.module.css
- pages/create-account/index.js
- pages/create-account/styles.module.css
- styles/globals.css
Added a Create Account Form component and utilized in the Create Account page. Pic below:
> GS-9: Add create account form component

- components/DeleteAccount/index.js
- components/DeleteAccount/styles.module.css
- components/LogOut/styles.module.css
- pages/settings/delete-account/index.js
- pages/settings/delete-account/styles.module.css
- pages/settings/logout/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-72
> GS-72: delete account component

- components/ChangePasswordForm/index.js
- components/ChangePasswordForm/styles.module.css
- components/SignInForm/index.js
- components/SignInForm/styles.module.css
- pages/create-account/index.js
- pages/settings/password/index.js
- pages/settings/password/styles.module.css
Create password form and link to change password subpage of settings.
> GS-55: Create password form

- components/LogOut/index.js
- pages/settings/logout/index.js
This closes out https://spacem8s.atlassian.net/browse/GS-78
> add necessary Links to LogOut component

- components/UserInfo/index.js
- components/UserInfo/styles.module.css
- pages/profile/index.js
- pages/profile/styles.module.css
- styles/globals.css
Added user info component and utilizing in Profile page. Pic below:
> GS-13: add UserInfo component to profile page

- components/DeleteAccount/index.js
- components/LogOut/index.js
- pages/settings/delete-account/index.js
This PR closes https://spacem8s.atlassian.net/browse/GS-79
> GS-79: create navigation Links in delete account component

- components/FeedbackForm/index.js
- components/FeedbackForm/styles.module.css
- pages/settings/feedback/index.js
- pages/settings/feedback/styles.module.css
Create feedback form for feedback subpage
.
> GS-66: Create feedback form

- components/FeedbackForm/index.js
- components/FeedbackForm/styles.module.css
Add navigation pathways to "Cancel" and "Submit" buttons.
> GS-77: Add navigation to feedback buttons

- components/SignInForm/index.js
- components/SignInForm/styles.module.css
- pages/create-account/index.js
- pages/sign-in/index.js
"Sign in" button navigates to Today page. "Sign Up" link navigates to Create Account page.
> GS-10: Add navigation to signin button and sign up link

- components/Statistics/index.js
- components/Statistics/styles.module.css
- components/StatsCard/index.js
- components/StatsCard/styles.module.css
- components/UserInfo/styles.module.css
- pages/profile/index.js
Completed Statistics component layout for Profile page and added reusable StatsCard component. Pic below:
> GS-73: profile page statistics layout

- components/ChangeGoalForm/index.js
- components/ChangeGoalForm/styles.module.css
- pages/settings/change-goal/index.js
- pages/settings/change-goal/styles.module.css
This PR closes https://spacem8s.atlassian.net/browse/GS-63
Updated photo
> GS-63: Implement change goal form and styles

- components/CreateAccountForm/index.js
- components/CreateAccountForm/styles.module.css
- pages/create-account/index.js
"Sign Up" button links to Today page. "Sign In" text links to SignIn Page.
> GS-6: Add navigation to CreateAccount page.

- components/ChangeGoalForm/index.js
- components/ChangeGoalForm/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-76
> GS-76: Inject navigation links and adjust css

- components/ChangePasswordForm/index.js
- components/ChangePasswordForm/styles.module.css
Each buttons individually navigates to the Settings page with its own Link component.
> GS-74: Add navigation to change password buttons

- components/AvatarContainer/index.js
- components/AvatarContainer/styles.module.css
- components/AvatarList/index.js
- components/AvatarList/styles.module.css
- pages/settings/change-avatar/index.js
- pages/settings/change-avatar/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-60
> implement avatar list layout and styles

- components/AvatarList/index.js
This PR closes https://spacem8s.atlassian.net/browse/GS-75
> GS-75: Link save and cancel buttons to settings page

- components/SettingsInputs/index.js
- components/SettingsInputs/styles.module.css
- pages/settings/index.js
- pages/settings/styles.module.css
Create settings input component and add it to settings page. Profile and button features are on separate tickets.
> GS-24: Add settings input fields

- components/WeeklyConsumption/index.js
- components/WeeklyConsumption/styles.module.css
- pages/today/index.js
Adding weekly consumption layout component. pic below:
> GS-35: Weekly consumption layout

- components/SettingsTopInfo/index.js
- components/SettingsTopInfo/styles.module.css
- pages/settings/index.js
- pages/settings/styles.module.css
No navigation for this ticket.
> GS-23: Addtop user info to Settings

- components/AvatarList/index.js
- components/ChangeGoalForm/index.js
- components/ChangePasswordForm/index.js
- components/CreateAccountForm/styles.module.css
- components/DeleteAccount/index.js
- components/DeleteAccount/styles.module.css
- components/FeedbackForm/index.js
- components/FeedbackForm/styles.module.css
- components/LargeLinkedButton/index.js
- components/LargeLinkedButton/styles.module.css
- components/LogOut/index.js
- components/LogOut/styles.module.css
- components/SignInForm/styles.module.css
- components/SmallLinkedButton/index.js
- components/SmallLinkedButton/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-82
> GS-82: create linked button components

- components/BottomTabs/styles.module.css
- components/SettingsButtons/index.js
- components/SettingsButtons/styles.module.css
- pages/settings/index.js
> GS-25: Setting button group with nav links (scroll down)

- components/BottomTabs/index.js
- components/BottomTabs/styles.module.css
Added Link to bottom tabs and made a fix for the position style.
> GS-80: add links to bottom tabs

- pages/profile/index.js
- pages/profile/styles.module.css
Added a link to the settings button on the profile page
> GS-19: add link to settings button on profile page

- components/ColorFilter/index.js
- components/ColorFilter/styles.module.css
- pages/eat/index.js
- pages/eat/styles.module.css
This PR closes https://spacem8s.atlassian.net/browse/GS-39
> GS-39: Color filter selection bar

- components/SettingsButtons/index.js
- components/SettingsInputs/index.js
> GS-84: Change password field into a button

- components/SignInForm/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-85
> GS-85: Change google sigin input type to button

- components/SettingsTopInfo/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-86
> GS-86: link avatar to change avatar subpage

- components/ChangePasswordForm/index.js
- components/CreateAccountForm/index.js
- components/FeedbackForm/index.js
- components/SignInForm/index.js
Updated the attributes for our forms to utilize "action" and "method", and got rid of unnecessary Links and anchors.
> GS-87: form submission correction

- components/CreateAccountForm/index.js
On this PR there are two possible solutions for creating an account.  One uses javascript, the other uses React's state which is commented out, but we need to choose which solution we'd like to use.
> GS-90: Add ability to create account using firebase auth

- components/ColorFilter/index.js
- components/CreateAccountForm/index.js
- components/FeedbackForm/index.js
- components/SettingsInputs/index.js
- context/AuthContext.js
- pages/_app.js
- pages/today/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-101
> GS-101: Implement auth state changed

- components/SignInForm/index.js
Registered user routes to Today page and Unregistered user returns an error while staying on signin page.
> GS-97: Add routing for signin

- components/CreateAccountForm/index.js
- components/DeleteAccount/index.js
- components/DeleteAccount/styles.module.css
- components/LogOut/index.js
- components/SmallLinkedButton/index.js
- context/AuthContext.js
This PR closes https://spacem8s.atlassian.net/browse/GS-96
> GS-96: email/pass delete account

- components/DeleteAccount/index.js
- components/Heading1/index.js
- components/Heading1/styles.module.css
- components/Heading2/index.js
- components/Heading2/styles.module.css
- components/LargeLinkedButton/styles.module.css
- components/SmallLinkedButton/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-116
Example of SmallLinkedButton, Heading1, Heading2 updates:
> GS-116: high fidelity reusable components

- components/ChangePasswordForm/index.js
- components/ChangePasswordForm/styles.module.css
- components/SmallLinkedButton/styles.module.css
- pages/settings/password/index.js
This closes out https://spacem8s.atlassian.net/browse/GS-114
> GS-114: high fidelity password page

- components/DeleteAccount/index.js
- components/DeleteAccount/styles.module.css
> GS-111: Add high fidelity CSS to delete account page

- components/SignInForm/styles.module.css
- pages/sign-in/index.js
- pages/sign-in/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-103
Updated:
> GS-103: sign in page/components css update

- components/CreateAccountForm/styles.module.css
- pages/create-account/index.js
- pages/create-account/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-104
> GS-104: high fidelity update for create account

- components/LogOut/index.js
- components/LogOut/styles.module.css
> GS-103: Add high fidelity CSS to logout page

- pages/sign-in/styles.module.css
- styles/globals.css
Listed below are color variables created:
> GS-117: Add CSS color variables

- components/FeedbackForm/index.js
- components/FeedbackForm/styles.module.css
- components/SmallLinkedButton/styles.module.css
- pages/settings/feedback/styles.module.css
> GS-112: Add high fidelity CSS to feedback page

- components/Heading1/styles.module.css
- pages/eat/styles.module.css
- pages/profile/styles.module.css
- pages/settings/styles.module.css
- pages/today/styles.module.css
> GS-107: Pages margin and vh fix

- components/ColorFilter/index.js
- components/ColorFilter/styles.module.css
- components/SearchFoodsList/styles.module.css
- pages/eat/index.js
> GS-118: add hifi css updates to eat page

- components/Heading1/styles.module.css
- components/Heading2/styles.module.css
- components/SettingsButtons/styles.module.css
- components/SettingsInputs/index.js
- components/SettingsInputs/styles.module.css
- components/SettingsTopInfo/index.js
- components/SettingsTopInfo/styles.module.css
- pages/settings/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-108
> GS-108: high fidelity settings page

- components/ChangeGoalForm/index.js
- components/ChangeGoalForm/styles.module.css
- pages/settings/change-goal/index.js
- pages/settings/change-goal/styles.module.css
> GS-110: Add high fidelity css to daily goal page

- components/ColorBreakdown/styles.module.css
- components/Statistics/index.js
- components/Statistics/styles.module.css
- components/StatsCard/styles.module.css
- components/UserInfo/index.js
- components/UserInfo/styles.module.css
This ticket closes out https://spacem8s.atlassian.net/browse/GS-105
> GS-105: profile page high fidelity update

- components/BottomTabs/index.js
- components/BottomTabs/styles.module.css
- package-lock.json
- package.json
> GS-119: add icons to bottom tabs nav

- pages/profile/index.js
- pages/profile/styles.module.css
> GS-121: add settings cog icon to profile page

- components/ColorBreakdown/index.js
- components/ColorBreakdown/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-122
> GS-122: total breakdown dummy data

- components/SearchFoodsList/index.js
- components/SearchFoodsList/styles.module.css
> GS-126: add background image to eat page

- components/AvatarList/index.js
- components/AvatarList/styles.module.css
- components/ColorFilter/index.js
- components/ColorFilter/styles.module.css
- components/SettingsTopInfo/index.js
- components/SettingsTopInfo/styles.module.css
- components/UserInfo/index.js
- components/UserInfo/styles.module.css
Added icons to eat page. Can be seen below in pic. Also updated way images were imported for avatar image to match import of icons.
> Gs 127 add icons to colorfilter

- components/TodayInfo/index.js
- components/TodayInfo/styles.module.css
- package-lock.json
- package.json
- styles/globals.css
- utils/populateDonutChartData.js
Add donut chart. Add logic to daily goal text below donut chart. Golden carrot appears inside of donut chart only once daily goal is reached. Logic requires a user object, so code is utilizing sample data for now.
> GS-124: Add donut chart on today page

- components/SettingsTopInfo/index.js
- components/SettingsTopInfo/styles.module.css
> GS-129: Add pen to change avatar settings

- pages/settings/change-avatar/index.js
- pages/settings/change-avatar/styles.module.css
- pages/settings/change-goal/index.js
- pages/settings/delete-account/index.js
- pages/settings/feedback/index.js
- pages/settings/logout/index.js
- pages/settings/password/index.js
> GS-136: Add navbar to all pages

- components/TodayInfo/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-135
> GS-135: fixed today info foods list

- components/BottomTabs/index.js
- pages/eat/index.js
- pages/profile/index.js
- pages/today/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-137
> GS-137: dynamically style bottom nav icons

- components/ColorBreakdown/styles.module.css
- components/TodayInfo/index.js
- pages/settings/styles.module.css
- utils/countColors.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-139
> GS-139: change graph fills

- components/ColorBreakdown/index.js
- components/ConsumptionHistory/index.js
- components/VerticalColorBreakdown/index.js
- components/VerticalColorBreakdown/styles.module.css
- utils/countColors.js
- utils/createHeightPercentages.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-143
> GS-143: count colors percentages and dynamic vertical bar width refactor

- components/ConsumptionHistory/index.js
- utils/organizeHistory.js
Included refactor of ConsumptionHistory
> GS-143: consumptionHistory refactor and organizeHistory utility creation

- components/Statistics/index.js
- utils/pickHighIcon.js
- utils/pickLowIcon.js
cleanup of unnecessary breaks in pick stats icon and implementation of main sample food data.
> Fast follow pick icon cleanup

- components/FeedbackForm/styles.module.css
- pages/settings/feedback/styles.module.css
This PR will close out https://spacem8s.atlassian.net/browse/GS-154
> GS-154: implement feedback responsive design for tablet

- components/DeleteAccount/styles.module.css
- components/LogOut/styles.module.css
- pages/settings/delete-account/styles.module.css
- pages/settings/logout/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-155
> GS-155: delete account and logout tablet responsive design

- components/SettingsButtons/styles.module.css
- components/SettingsInputs/index.js
- components/SettingsInputs/styles.module.css
- components/SettingsTopInfo/index.js
- components/SettingsTopInfo/styles.module.css
- pages/settings/index.js
- pages/settings/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-149
> GS-149: implement settings responsive design for tablet

- components/CreateAccountForm/styles.module.css
- pages/create-account/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-145
> GS-145: create-account responsive tablet

- components/AvatarList/styles.module.css
- components/SignInForm/styles.module.css
- pages/settings/change-avatar/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-150
> GS-150: implement change avatar tablet responsive design

- components/SignInForm/styles.module.css
- pages/sign-in/styles.module.css
> GS-144: Add tablet responsive design to signIn page

- components/ChangePasswordForm/styles.module.css
- components/CreateAccountForm/styles.module.css
- pages/settings/password/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-153
> GS-153: password tablet

- components/ChangeGoalForm/styles.module.css
- pages/settings/change-goal/index.js
- pages/settings/change-goal/styles.module.css
> GS-152: Add responsive tablet design to Change Goal page

- components/ColorBreakdown/styles.module.css
- components/Statistics/styles.module.css
- components/StatsCard/styles.module.css
- components/UserInfo/index.js
- components/UserInfo/styles.module.css
- pages/profile/index.js
- pages/profile/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-148
> GS-148: implement profile responsive tablet design

- pages/settings/about/index.js
- pages/settings/about/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-157
> GS-157: implement about responsive tablet design

- components/ColorFilter/index.js
- components/ColorFilter/styles.module.css
- components/SearchFoodsForm/styles.module.css
- components/SearchFoodsList/styles.module.css
- pages/eat/styles.module.css
> GS-147: eat page tablet layout

- components/ChangeGoalForm/styles.module.css
> GS-152: Increased picker box and arrow size

- context/AuthContext.js
- model/food/index.js
- model/log/index.js
- model/user/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-162
> GS-162: user and food model skeletons

- components/AvatarList/index.js
- components/ChangeGoalForm/index.js
- components/ChangePasswordForm/index.js
- components/ColorBreakdown/index.js
- components/ConsumptionHistory/index.js
- components/CreateAccountForm/index.js
- components/DeleteAccount/index.js
- components/FeedbackForm/index.js
- components/LogOut/index.js
- components/SearchFoodsForm/index.js
- components/SearchFoodsList/index.js
- components/SettingsInputs/index.js
- components/SettingsTopInfo/index.js
- components/SignInForm/index.js
- components/Statistics/index.js
- components/TodayInfo/index.js
- components/UserInfo/index.js
- pages/profile/index.js
- pages/settings/index.js
- pages/today/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-164
> GS-164: pull uid in the pages/components we need them

- components/SearchFoodsForm/index.js
- components/SearchFoodsForm/styles.module.css
- model/foodEntry/index.js
- model/user/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-167
> GS-167: createFoodEntry implementation into eat page

- components/Statistics/index.js
- model/user/index.js
- pages/profile/index.js
this branch add the getUser model and uses it for getting the user day streak and golden carrots from firestore.
> GS-176: get user object from firestore

- components/TodayInfo/index.js
- model/foodEntry/index.js
- pages/today/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-175
> GS-175: implement getCurrentDay foodEntry model and apply to TodayInfo

- components/UserInfo/index.js
- pages/profile/index.js
This branch adds more user info from db to profile page such as selected avatar and name.
> GS-186: add more user info to profile from db

- components/AvatarList/styles.module.css
> GS-185: Clean up avatar style code

- model/foodEntry/index.js
- model/masterFoodList/index.js
- model/user/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-191
> GS-191: refactor model classes

- model/foodEntry/index.js
- utils/alphabetizeFoods.js
- utils/filterByDate.js
- utils/populateDonutChartData.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-190
> GS-190: renamed non specific variables

- components/CreateAccountForm/index.js
- components/SignInForm/index.js
- context/AuthContext.js
- firebase.js
- model/user/index.js
- pages/sign-in/index.js
- utils/createNewUserDataModel.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-89
> GS-89: google signup login

- components/ChangeGoalForm/styles.module.css
- components/SearchFoodsButtons/index.js
- components/SearchFoodsButtons/styles.module.css
- pages/eat/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-201
> GS-201: disabled eat button on no selection and minor css cleanup

- components/Loading/index.js
- pages/_app.js
- pages/_document.js
- styles/loader.js
this branch will add a preloader to the app when there is a hard refresh, instead of a blank white screen
> GS-204: Fix White Loading Screen

- components/CreateAccountForm/index.js
- components/LogOut/index.js
- components/SignInForm/index.js
- components/WithUnprotected/index.js
- context/AuthContext.js
- model/foodEntry/index.js
- model/user/index.js
- pages/create-account/index.js
- pages/eat/index.js
- pages/sign-in/index.js
- pages/today/index.js
This PR attempts to close out 2 tickets:
https://spacem8s.atlassian.net/browse/GS-205
https://spacem8s.atlassian.net/browse/GS-206
This will require mindful testing before approving.
> GS-205: withUnprotected, google auth refactor, reset isGoalComplete

- components/SignInForm/index.js
- components/SignInForm/styles.module.css
- pages/sign-in/styles.module.css
- utils/validateName.js
- utils/validatePassword.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-195
> GS-195: login input validation

- components/SearchFoodsButtons/index.js
- model/user/index.js
- pages/today/index.js
- utils/createNewUserDataModel.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-181
> GS-181: implemented clear daystreak logic

- components/PageContainer/index.js
- components/PageContainer/styles.module.css
- pages/create-account/index.js
- pages/create-account/styles.module.css
- pages/settings/about/styles.module.css
- pages/settings/change-avatar/index.js
- pages/settings/change-goal/index.js
- pages/settings/change-goal/styles.module.css
- pages/settings/delete-account/index.js
- pages/settings/delete-account/styles.module.css
- pages/settings/feedback/index.js
- pages/settings/feedback/styles.module.css
- pages/settings/logout/index.js
- pages/settings/logout/styles.module.css
- pages/settings/password/styles.module.css
- pages/settings/styles.module.css
- pages/sign-in/index.js
- pages/sign-in/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-207
> GS-207-reusable page component that covers over half of our pages

- components/ChangePasswordForm/index.js
- components/ChangePasswordForm/styles.module.css
- components/SignInForm/index.js
- masterFoodLibrary/masterFoodLibrary.js
> GS-202: New password visual confirmation

- components/ChangePasswordForm/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-199
> GS-199: implement validation for change password form

- components/SettingsInputs/index.js
- components/SettingsInputs/styles.module.css
- components/SettingsTopInfo/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-198
> GS-198: change email input validation

- components/ChangePasswordForm/index.js
- components/ChangePasswordInput/index.js
- components/ChangePasswordInput/styles.module.css
- components/CreateAccountForm/index.js
- components/CreateAccountPasswordInput/index.js
- components/CreateAccountPasswordInput/styles.module.css
- components/PageContainer/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-213
> GS-213: modularize password/confirm password fields for change password and create account

- components/BottomTabs/styles.module.css
- components/ChangeGoalForm/styles.module.css
- components/ChangePasswordForm/styles.module.css
- components/ChangePasswordInput/styles.module.css
- components/ColorBreakdown/styles.module.css
- components/ColorFilter/styles.module.css
- components/ConsumptionHistory/styles.module.css
- components/CreateAccountForm/styles.module.css
- components/CreateAccountPasswordInput/styles.module.css
- components/DeleteAccount/styles.module.css
- components/FeedbackForm/styles.module.css
- components/Heading2/styles.module.css
- components/LargeLinkedButton/styles.module.css
- components/LogOut/styles.module.css
- components/SearchFoodsButtons/styles.module.css
- components/SearchFoodsForm/styles.module.css
- components/SearchFoodsList/styles.module.css
- components/SettingsButtons/styles.module.css
- components/SettingsInputs/styles.module.css
- components/SettingsTopInfo/styles.module.css
- components/SignInForm/styles.module.css
- components/SmallLinkedButton/styles.module.css
- components/Statistics/styles.module.css
- components/StatsCard/styles.module.css
- components/TodayInfo/styles.module.css
- components/UserInfo/styles.module.css
- pages/settings/about/styles.module.css
This branch adds a min-height property to most of components in app so they don't scale to tablet layout unless there is the proper height
> GS-217: add min-height to components

- components/SettingsEmailForm/index.js
- components/SettingsEmailForm/styles.module.css
- components/SettingsNameForm/index.js
- components/SettingsNameForm/styles.module.css
- pages/settings/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-215
> GS-215: refactor settings inputs

- components/BottomTabs/styles.module.css
- components/Sidebar/index.js
- components/Sidebar/styles.module.css
- pages/eat/index.js
- pages/profile/index.js
- pages/settings/about/index.js
- pages/settings/change-avatar/index.js
- pages/settings/change-goal/index.js
- pages/settings/delete-account/index.js
- pages/settings/feedback/index.js
- pages/settings/index.js
- pages/settings/logout/index.js
- pages/settings/password/index.js
- pages/today/index.js
- pages/today/styles.module.css
This branch adds the sidebar component to every page when the view-width >= 1024px. Example page below:
> GS-230: add sidebar component

- components/CreateAccountForm/index.js
- components/CreateAccountForm/styles.module.css
- components/CreateAccountPasswordInput/index.js
- pages/create-account/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-234
> GS-234: implement create account error handling

- components/DeleteAccount/index.js
- components/DeleteAccount/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-235
> GS-235: implement delete account error handling

- components/ChangeGoalForm/styles.module.css
> GS-225: Add desktop responsive design to edit goal

- components/ConsumptionHistory/styles.module.css
- components/Heading1/styles.module.css
- components/StatsCard/styles.module.css
- components/TodayInfo/styles.module.css
- components/TodayStatistics/index.js
- components/TodayStatistics/styles.module.css
- components/TodayUserInfo/index.js
- components/TodayUserInfo/styles.module.css
- pages/today/index.js
- pages/today/styles.module.css
> GS-222: Today page desktop layout

- components/FeedbackForm/index.js
- components/FeedbackForm/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-242
> GS-242: made state controlled form and added error css

- components/ChangePasswordForm/index.js
- components/ChangePasswordForm/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-241
> GS-241: change password error handling

- components/ChangeGoalForm/index.js
- components/ChangeGoalForm/styles.module.css
- pages/settings/change-goal/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-239
> GS-239: change goal error handling

- components/EatColorFilter/index.js
- components/EatColorFilter/styles.module.css
- components/EatFoodsForm/index.js
- components/EatFoodsForm/styles.module.css
- components/EatFormButtons/index.js
- components/TodayFoodList/index.js
- components/TodayFoodList/styles.module.css
- components/TodayGoalInfo/index.js
- components/TodayGoalInfo/styles.module.css
- pages/eat/index.js
- pages/eat/styles.module.css
> GS-223: Add eat page desktop responsive layout

- components/CreateAccountForm/styles.module.css
- components/CreateAccountPasswordInput/styles.module.css
- components/PageContainer/index.js
- components/PageContainer/styles.module.css
- components/SignInForm/styles.module.css
- pages/create-account/index.js
- pages/create-account/styles.module.css
- pages/sign-in/index.js
- pages/sign-in/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-247
> GS-247: sign in/create account fast follow

- components/SettingsEmailForm/index.js
- components/SettingsEmailForm/styles.module.css
- components/SettingsNameForm/index.js
- components/SettingsNameForm/styles.module.css
- pages/create-account/index.js
- pages/sign-in/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-236 and https://spacem8s.atlassian.net/browse/GS-237
> GS-236/237: error handling for change name and change email

- components/EatFoodsForm/index.js
- components/EatFormButtons/index.js
- components/EatFormButtons/styles.module.css
This PR closes out https://spacem8s.atlassian.net/browse/GS-238
> GS-238: add food error handling

- components/BottomTabs/index.js
- components/BottomTabs/styles.module.css
- components/ProfileGraph/styles.module.css
- components/ProfileStatistics/styles.module.css
- components/ProfileUserInfo/styles.module.css
- components/StatsCard/styles.module.css
- pages/profile/index.js
- pages/profile/styles.module.css
This branch adds a responsive layout for the profile page and add some minor updates to the bottom tabs css.
> GS-221: profile page responsive layout

- components/FeedbackForm/index.js
- components/FeedbackForm/styles.module.css
- pages/settings/feedback/index.js
> GS-226: Add responsive design to feedback form

- components/LargeLinkedButton/styles.module.css
- components/SettingsButtons/styles.module.css
- components/SettingsEmailForm/index.js
- components/SettingsEmailForm/styles.module.css
- components/SettingsNameForm/styles.module.css
- components/SettingsTopInfo/styles.module.css
- pages/settings/styles.module.css
> GS-224: add dekstop responsive layout to settings page

- pages/settings/logout/styles.module.css
> GS-228: Add responsive desktop design for logout page

- components/ChangeGoalForm/index.js
- components/DeleteAccount/index.js
- components/EatFormButtons/index.js
- components/LogOut/index.js
- components/TodayGoalInfo/index.js
- context/AuthContext.js
- context/UserContext.js
- model/user/index.js
- pages/_app.js
- pages/eat/index.js
- pages/profile/index.js
- pages/settings/change-goal/index.js
- pages/settings/feedback/index.js
- pages/settings/index.js
- pages/today/index.js
- routers/withProtected/index.js
- routers/withUnprotected/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-250
> GS-250: realtime updates for db user object

- utils/__tests__/chunkArray.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-262
> GS-262: testing for chunkArray

- utils/__tests__/createHeightPercentages.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-264
> GS-264: create height percentages tests

- utils/__tests__/createNewUserDataModel.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-265
> GS-265: implement createNewUserDataModel tests

- utils/__tests__/filterByDate.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-266
> GS-266: filterByDate tests

- utils/__tests__/filterFoodsForSearch.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-268
> GS-268: implement filterFoodsForSearch tests

- utils/__tests__/organizeFoodHistory.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-269
> GS-269: implement organizeFoodHistory tests

- utils/__tests__/alphabetizeFoods.test.js
- utils/__tests__/checkHighestColor.test.js
- utils/__tests__/checkLowestColor.test.js
- utils/__tests__/chunkArray.test.js
- utils/__tests__/countColors.test.js
- utils/__tests__/createHeightPercentages.test.js
- utils/__tests__/createNewUserDataModel.test.js
- utils/__tests__/filterByDate.test.js
- utils/__tests__/filterByDateRange.test.js
- utils/__tests__/organizeFoodHistory.test.js
- utils/__tests__/pickHighIcon.test.js
- utils/__tests__/pickLowIcon.test.js
- utils/__tests__/populateDonutChartData.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-275
> GS-275: fast follow

- components/ChangeAvatarList/styles.module.css
- components/Sidebar/index.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-319
> GS-319: fa error and css fast follow

- components/About/index.js
- components/About/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-277
> GS-277: implement About component tests

- components/AddButton/index.js
- components/AddButton/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-278
> GS-278: implement AddButton tests

- components/About/index.test.js
- components/BottomTabs/index.js
- components/BottomTabs/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-279
> GS-279: implement BottomTabs test

- components/About/index.test.js
- components/AddButton/index.test.js
- components/BottomTabs/index.test.js
- components/ChangeGoalForm/index.js
- components/ChangeGoalForm/index.test.js
- components/EatColorFilter/index.test.js
- components/EatFoodsList/index.test.js
- components/TodayUserInfo/index.test.js
- jest.config.js
- jest.resolver.js
- jest.setup.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-281
> GS-281: change goal form tests

- components/ChangePasswordForm/index.js
- components/ChangePasswordForm/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-282
> GS-282: changePasswordForm tests

- components/ChangePasswordInput/index.js
- components/ChangePasswordInput/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-283
> GS-283: ChangePasswordInput tests

- components/ChangePasswordForm/index.test.js
- components/CreateAccountForm/index.js
- components/CreateAccountForm/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-284
> GS-284: CreateAccountForm tests

- components/CreateAccountPasswordInput/index.js
- components/CreateAccountPasswordInput/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-285
> GS-285: implement CreateAccountPasswordInput tests

- components/DeleteAccount/index.js
- components/DeleteAccount/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-286
> GS-286: implement DeleteAccount tests

- components/Heading1/index.test.js
- components/Heading2/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-292 and https://spacem8s.atlassian.net/browse/GS-293
> GS-292/293: heading1 and heading2 tests

- components/FeedbackForm/index.js
- components/FeedbackForm/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-291
> GS-291: FeedbackForm tests

- components/HomeGraphContainer/index.js
- components/HomeGraphContainer/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-295
> GS-295: HomeGraphContainer tests

- components/HomeImages/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-296
> GS-296: HomeImages tests

- components/HomeStatsContainer/index.js
- components/HomeStatsContainer/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-297
> GS-297: implement HomeStatsContainer tests

- components/LargeLinkedButton/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-298
> GS-298: LargeLinkedButton tests

- components/LogOut/index.js
- components/LogOut/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-300
> GS-300: implement LogOut tests

- components/PageContainer/index.js
- components/PageContainer/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-301
> GS-301: implement PageContainer tests

- components/ProfileGraph/index.js
- components/ProfileGraph/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-302
> GS-302: implement ProfileGraph tests

- components/ProfileStatistics/index.js
- components/ProfileStatistics/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-303
> GS-303: implement ProfileStatistics tests

- components/ProfileUserInfo/index.js
- components/ProfileUserInfo/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-304
> GS-304: ProfileUserInfo tests

- components/SettingsButtons/index.js
- components/SettingsButtons/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-305
> GS-305: implement SettingsButtons tests

- components/SettingsEmailForm/index.js
- components/SettingsEmailForm/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-306
> GS-306: implement SettingsEmailForm tests

- components/SettingsNameForm/index.js
- components/SettingsNameForm/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-307
> GS-307: SettingsNameForm tests

- components/SettingsTopInfo/index.js
- components/SettingsTopInfo/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-308
> GS-308: SettingsTopInfo tests

- components/ChangeAvatarList/index.test.js
- components/ChangeGoalForm/index.test.js
- components/ChangePasswordForm/index.test.js
- components/CreateAccountForm/index.test.js
- components/DeleteAccount/index.js
- components/DeleteAccount/index.test.js
- components/EatFormButtons/index.js
- components/EatFormButtons/index.test.js
- components/FeedbackForm/index.test.js
- components/LogOut/index.test.js
- components/SettingsEmailForm/index.test.js
- components/SettingsNameForm/index.test.js
- components/SignInForm/index.js
- components/SignInForm/index.test.js
- utils/__tests__/alphabetizeFoods.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-324
> GS-324: error handling tests

- pages/profile/index.js
- pages/profile/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-329
> GS-329: ProfilePage tests

- pages/eat/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-328
> GS-328: Eat page tests

- pages/today/index.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-332
> GS-332: today page tests

- __tests__/about.test.js
- __tests__/create-account.test.js
- __tests__/eat.test.js
- __tests__/feedback.test.js
- __tests__/logout.test.js
- __tests__/password.test.js
- __tests__/profile.test.js
- __tests__/sign-in.test.js
- __tests__/today.test.js
This PR closes out https://spacem8s.atlassian.net/browse/GS-341
> GS-341: move page tests to seperate folder
